'''
Get some data for PINN's parameter discovery demo.

The data is generated by the solver of Poisson's equation with PINN.
'''

import torch
import torch.nn as nn
from used_funcs import *

path = ""

# load the model
model = PINN(hidden_layers=100)
model.load_state_dict(torch.load(path + 'model.pth'))

# get 5000 data points
data_r = batch_get_random_xy(5000, location=None, requires_grad=False)
data_phi = model(data_r)
data = torch.cat((data_r, data_phi), dim=1)

# save the data
torch.save(data, path + 'data.pth')
